### ISSUE TITLE
bench for nqp-moar won't finish the 15/65 while_pushme forever

### ISSUE THREAD

**Issue by chenryn** [japhb/perl6-bench#13]
I try to run `timeall --verbose rakudo-moar nqp-moar` to see the debug log. And found the `rakudo-moar` would finish 15/65 test after "performing 2 runs at scale 21 (work 2097152)", but the `nqp-moar` has been running to scale 3441 now and not even stop! 

```
... performing 2 runs at scale 317 (work 2305843009213693952)
    1
    2
... performing 2 runs at scale 318 (work 4611686018427387904)
    1
    2
... performing 2 runs at scale 319 (work 9223372036854775808)
    1
    2
... performing 2 runs at scale 320 (work 1)
    1
    2
... performing 2 runs at scale 321 (work 2)
    1
```

Everytime it reach the `9223372036854775808` then re work from 1.

**Comment by japhb** [comment]
I forgot we had an issue open for this (timotimo++ for remembering), but current perl6-bench as of mid-January should have fixed this finally.  Sorry for the delayed response!
